version: '3.8'

services:
  web:
    build: .
    command: gunicorn resume_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=resume_app.settings
    restart: always

volumes:
  static_volume:
  media_volume:
